### ISSUE TITLE
The design is not original.

### ISSUE THREAD

**Issue by chrische-xx** [ranan-usp/mpw7_analog#1]
Why are you resubmitting [my sar design](https://github.com/chrische-xx/mpw6) without any changes  to the [efabless mpw7 shuttle](https://platform.efabless.com/projects/1272) and call it your own?

Not that I mind at all when people resuse the design, but I think that if you submit it to efabless you should at least have made some improvements to it and not just copied the original design.

**Comment by ranan-usp** [comment]
I apologize for any misunderstanding.
I am studying automatic layout design.
I designed your compartor and cdac layout automatically.
Sample and hold Circuit layout will also be automatically designed．

**Comment by ranan-usp** [comment]
I apologize for reusing your design without telling you.
